---
title: "Age at Each Wave"
author: "cfm"
date: "2/4/2021"
output: html_document
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)

```

```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}

## Load required packages ##

packages <-  c("tidyverse",
               "nlme", 
               "data.table", 
               "parallel","lubridate",
               "mgcv",  "broom")

lapply(packages, library, character.only = TRUE)
```

```{r Setting root path}

## cfm root path 

root_path = "~/Desktop/Projects/tag/"

```

```{r pulling in csv}

## importing doc pulled from redcap with IDs and all session dates 

long_doc <- read.csv(paste0(root_path, "long_doc.csv"),
                     stringsAsFactors = FALSE)

ace <- read.csv(paste0(root_path, "age_ACE.csv"),
                stringsAsFactors = FALSE)

dob <- read.csv(paste0(root_path, "TAG_DOB_SessionDates.csv"),
                stringsAsFactors = FALSE) %>%
  select(tagid, dob)

```

```{r loading in function (age_calc) to calculate precise age}

age_calc <- function(dob, enddate=Sys.Date(), units='months', precise=TRUE){
  if (!inherits(dob, "Date") | !inherits(enddate, "Date")) {
    stop("Both dob and enddate must be Date class objects")
  }
  if (any(enddate < dob)) {
    stop("End date must be a date after date of birth")
  }
  start <- as.POSIXlt(dob)
  end <- as.POSIXlt(enddate)
  if (precise) {
    start_is_leap <- ifelse(start$year %% 400 == 0, TRUE,
                            ifelse(start$year %% 100 == 0, FALSE,
                                   ifelse(start$year %% 4 == 0, TRUE, FALSE)))
    end_is_leap <- ifelse(end$year %% 400 == 0, TRUE,
                          ifelse(end$year %% 100 == 0, FALSE,
                                 ifelse(end$year %% 4 == 0, TRUE, FALSE)))
  }
  if (units == 'days') {
    result <- difftime(end, start, units = 'days')
  } else if (units == 'months') {
    months <- vapply(mapply(seq, as.POSIXct(start), as.POSIXct(end),
                            by = 'months', SIMPLIFY = FALSE),
                     length, FUN.VALUE = length(start)) - 1
    # length(seq(start, end, by='month')) - 1
    if (precise) {
      month_length_end <- ifelse(end$mon == 1 & end_is_leap, 29,
                                 ifelse(end$mon == 1, 28,
                                        ifelse(end$mon %in% c(3, 5, 8, 10),
                                               30, 31)))
      month_length_prior <- ifelse((end$mon - 1) == 1 & start_is_leap, 29,
                                   ifelse((end$mon - 1) == 1, 28,
                                        ifelse((end$mon - 1) %in% c(3, 5, 8, 10),
                                                 30, 31)))
      month_frac <- ifelse(end$mday > start$mday,
                           (end$mday - start$mday) / month_length_end,
                           ifelse(end$mday < start$mday,
                                  (month_length_prior - start$mday) /
                                    month_length_prior +
                                    end$mday/month_length_end, 0.0))
      result <- months + month_frac
    }else{
      result <- months
    }
  } else if (units == 'years') {
    years <- vapply(mapply(seq, as.POSIXct(start), as.POSIXct(end),
                           by = 'years', SIMPLIFY = FALSE),
                    length, FUN.VALUE = length(start)) - 1
    if (precise) {
      start_length <- ifelse(start_is_leap, 366, 365)
      end_length <- ifelse(end_is_leap, 366, 365)
      start_day <- ifelse(start_is_leap & start$yday >= 60,
                          start$yday - 1,
                          start$yday)
      end_day <- ifelse(end_is_leap & end$yday >= 60,
                        end$yday - 1,
                        end$yday)
      year_frac <- ifelse(start_day < end_day,
                          (end_day - start_day)/end_length,
                          ifelse(start_day > end_day,
                                 (start_length - start_day) / start_length +
                                   end_day / end_length, 0.0))
      result <- years + year_frac
    }else{
      result <- years
    }
  }else{
    stop("Unrecognized units. Please choose years, months, or days.")
  }
  return(result)
}

```

```{r Merging and cleaning docs}

## TAG General merge

whole <- full_join(long_doc, dob, by="tagid") %>%
   filter(!is.na(session_date),
          !is.na(dob))

## converting to date class

whole$session_date <- as.Date(whole$session_date, format = "%m/%d/%Y")
whole$dob <- as.Date(whole$dob, format = "%m/%d/%Y")

## calculating age from DOB & session dates

whole$age <- age_calc(whole$dob, enddate = whole$session_date, units = "years", precise = TRUE)

## converting ace session dates to date class for merge 

#ace$session_date <- as.Date(ace$session_date)

## merging data sets

#whole <- full_join(age_all, ace) 

## renaming wave labels to be more readable

whole <- whole %>%
  mutate(wave=ifelse(wave=="wave_1_scheduling_arm_1", "W1",
                           ifelse(wave=="wave_2_scheduling_arm_1","W2",
                                  ifelse(wave=="wave_3_scheduling_arm_1","W3",
                                         ifelse(wave=="wave_4_scheduling_arm_1", "W4",
                                                ifelse(wave=="sos_arm_1","SOS1",
                                                       ifelse(wave=="C1","COV1",
                                                              ifelse(wave=="C2","COV2",
                                                                     ifelse(wave=="C3", "COV3",
                              wave))))))))) %>%
  mutate(wave=as.factor(wave)) 

## reordering levels

whole$wave <- factor(whole$wave, levels=c("W1", "W2", "SOS1", "W3", "COV1", "W4", "COV2", "COV3"))


```

```{r actual study design graph w/ shapes !!}

## creating a doc ordering IDs by timepoints, age and ID

study_design <- whole[order(whole$wave, whole$age, whole$tagid),]

## creating levels using ordered doc 

whole <- study_design %>%
  mutate(Rank_nr=as.numeric(factor(tagid,levels=unique(tagid))))

## creating visualization 

tag_study_design_plot<- ggplot(whole,
                           aes(x=age,
                               y=Rank_nr,
                               group=tagid,
                               col=wave,
                               shape=wave)) + 
  geom_point(alpha=1) + 
  geom_line(alpha=.4) +
  theme(axis.text.y = element_blank()) +
  scale_color_manual(name= "Wave",
                     labels = c("W1", "W2", "SOS1", "W3", "COV1", "COV2", "COV3", "W4"),
                     values = c("#5445b1", "#749dae", "#f3c483", "#5c1a33", "#cd3341","#FE5D26", "#FFA0AC", "#B4DC7F"))  +
  scale_shape_manual(name= "Wave",
              labels= c("W1", "W2", "SOS1", "W3", "COV1", "COV2", "COV3", "W4"),
              values = c(0, 1, 2, 5, 6, 7, 10, 14))+
  ylab("") +
  xlab("Age (years)")+
  scale_y_discrete(breaks=NULL) +
  theme_minimal()

## viewing plot 

print(tag_study_design_plot)

## saving png of plot 

ggsave(filename="tag_study_design_w_shapes.png",
       plot=tag_study_design_plot, width=6, height=5, units='in', dpi=300)



```

```{r just waves!!}

##creating separate w1-w4 doc 

wave_1 <- whole[which(whole$wave == "W1"),]
wave_2 <- whole[which(whole$wave == "W2"),]
wave_3 <- whole[which(whole$wave == "W3"),]
wave_4 <- whole[which(whole$wave == "W4"),]

just_waves <- full_join(wave_1, wave_2)
just_waves <- full_join(just_waves, wave_3)
just_waves <- full_join(just_waves, wave_4)

## creating a doc ordering IDs by timepoints, age and ID

waves_study_design <- just_waves[order(just_waves$wave, just_waves$age, just_waves$tagid),]

## creating levels using ordered doc 

just_waves <- waves_study_design %>%
  mutate(Rank_nr=as.numeric(factor(tagid,levels=unique(tagid))))

## creating visualization 

tag_waves_study_design_plot<- ggplot(just_waves,
                           aes(x=age,
                               y=Rank_nr,
                               group=tagid,
                               col=wave,
                               shape=wave)) + 
  geom_point(alpha=1) + 
  geom_line(alpha=.4) +
  theme(axis.text.y = element_blank()) +
  scale_color_manual(name= "Wave",
                     labels = c("W1", "W2", "W3",  "W4"),
                     values = c("#5445b1", "#749dae", "#f3c483", "#5c1a33"))  +
  scale_shape_manual(name= "Wave",
              labels= c("W1", "W2",  "W3", "W4"),
              values = c(0, 1, 2, 5))+
  ylab("") +
  xlab("Age (years)")+
  scale_y_discrete(breaks=NULL) +
  theme_minimal()

## viewing plot 

print(tag_waves_study_design_plot)

## saving png of plot 

ggsave(filename="tag_waves_tudy_design_w_shapes.png",
       plot=tag_waves_study_design_plot, width=6, height=5, units='in', dpi=300)



```

```{r just waves 1-3 + sos!!}

##creating separate w1-w3 + sos doc 

wave_1 <- whole[which(whole$wave == "W1"),]
wave_2 <- whole[which(whole$wave == "W2"),]
wave_3 <- whole[which(whole$wave == "W3"),]
sos <- whole[which(whole$wave == "W4"),]

just_waves <- full_join(wave_1, wave_2)
just_waves <- full_join(just_waves, wave_3)
just_waves <- full_join(just_waves, wave_4)

## creating a doc ordering IDs by timepoints, age and ID

waves_study_design <- just_waves[order(just_waves$wave, just_waves$age, just_waves$tagid),]

## creating levels using ordered doc 

just_waves <- waves_study_design %>%
  mutate(Rank_nr=as.numeric(factor(tagid,levels=unique(tagid))))

## creating visualization 

tag_waves_study_design_plot<- ggplot(just_waves,
                           aes(x=age,
                               y=Rank_nr,
                               group=tagid,
                               col=wave,
                               shape=wave)) + 
  geom_point(alpha=1) + 
  geom_line(alpha=.4) +
  theme(axis.text.y = element_blank()) +
  scale_color_manual(name= "Wave",
                     labels = c("W1", "W2", "W3",  "W4"),
                     values = c("#5445b1", "#749dae", "#f3c483", "#5c1a33"))  +
  scale_shape_manual(name= "Wave",
              labels= c("W1", "W2",  "W3", "W4"),
              values = c(0, 1, 2, 5))+
  ylab("") +
  xlab("Age (years)")+
  scale_y_discrete(breaks=NULL) +
  theme_minimal()

## viewing plot 

print(tag_waves_study_design_plot)

## saving png of plot 

ggsave(filename="tag_waves_tudy_design_w_shapes.png",
       plot=tag_waves_study_design_plot, width=6, height=5, units='in', dpi=300)



```


```{r just ACE}

## sorting IDs by number of timepoints

ace <- ace %>%
  mutate(wave=ifelse(wave=="C1","COV1",
                     ifelse(wave=="C2","COV2",
                            ifelse(wave=="C3", "COV3",
                              wave)))) %>%
  mutate(wave=as.factor(wave)) 

## creating a doc ordering IDs by timepoints, age and ID

study_design_ace <- ace[order(ace$wave, ace$age, ace$TAGID),]

## creating levels using ordered doc 

ace <- study_design_ace %>%
  mutate(Rank_nr=as.numeric(factor(TAGID,levels=unique(TAGID))))

## creating visualization 

ace_study_design_plot<- ggplot(ace,
                           aes(x=age,
                               y=Rank_nr,
                               group=TAGID,
                               col=wave,
                               shape=wave)) + 
  geom_point(alpha=1) + 
  geom_line(alpha=.4) +
  theme(axis.text.y = element_blank()) +
  scale_color_manual(name= "Wave",
                     labels = c("COV1", "COV2", "COV3"),
                     values = c("#5445b1", "#749dae", "#f3c483"))  +
  scale_shape_manual(name= "Wave",
              labels= c("COV1", "COV2", "COV3"),
              values = c(0, 1, 2))+
  ylab("") +
  xlab("Age (years)")+
  scale_y_discrete(breaks=NULL) +
  theme_minimal()

## viewing plot 

print(ace_study_design_plot)

## saving png of plot 

ggsave(filename="ace_study_design_w_shapes.png",
       plot=ace_study_design_plot, width=6, height=5, units='in', dpi=300)

```

```{r adding session dates for W4 to TAG_DOB}

dob_full <- read.csv(paste0(root_path, "TAG_DOB_SessionDates.csv"),
                stringsAsFactors = FALSE)

w4_dates_s1 <- read.csv(paste0(root_path, "W4_S1_complete.csv"),
                stringsAsFactors = FALSE)

w4_dates_s1 <-w4_dates_s1 %>%
  mutate(no_underscores=paste0("TAG",
                               substring(tagid,first=5,last=length(tagid))))
 w4_dates_s1 <- w4_dates_s1[c(-1)]
 w4_dates_s1 <- w4_dates_s1[c(2,1)]
 colnames(w4_dates_s1)[1] <- "tagid"

w4_dates_s2 <- read.csv(paste0(root_path, "W4_completed_S2.csv"),
                stringsAsFactors = FALSE)

w4_dates_s2 <-w4_dates_s2 %>%
  mutate(no_underscores=paste0("TAG",
                               substring(tagid,first=5,last=length(tagid))))
 w4_dates_s2 <- w4_dates_s2[c(-1)]
 w4_dates_s2 <- w4_dates_s2[c(2,1)]
 colnames(w4_dates_s2)[1] <- "tagid"

dob_full <- full_join(dob_full, w4_dates_s1, by = "tagid")
dob_full <- full_join(dob_full, w4_dates_s2, by = "tagid")

dob_full  <- dob_full[c(1,2,3,4,5,6,7,8,17,18,9,10,11,12,13,14,15,16)]

 ## converting to date class

dob_full$W4S1_Date <- as.Date(dob_full$W4S1_Date, "%m/%d/%y")
dob_full$W4S2_Date <- as.Date(dob_full$W4S2_Date, "%m/%d/%y")
dob_full$dob <- as.Date(dob_full$dob, "%m/%d/%y")

## calculating age from DOB & session dates

w4s1_age <- dob_full %>%
  filter(!is.na(dob_full$W4S1_Date))

w4s1_age <- w4s1_age %>%
  select(tagid, dob, W4S1_Date)

w4s1_age$W4S1_Age <- age_calc(w4s1_age$dob, enddate = w4s1_age$W4S1_Date, units = "years", precise = TRUE)

w4s2_age <- dob_full %>%
  filter(!is.na(dob_full$W4S2_Date))

w4s2_age <- w4s2_age %>%
  select(tagid, dob, W4S2_Date)

w4s2_age$W4S2_Age <- age_calc(w4s2_age$dob, enddate = w4s2_age$W4S2_Date, units = "years", precise = TRUE)

w4s1_age <- w4s1_age %>%
  select(-dob,-W4S1_Date)

w4s2_age <- w4s2_age %>%
  select(-dob,-W4S2_Date)

dob_full <- full_join(dob_full, w4s1_age, by = "tagid")
dob_full <- full_join(dob_full, w4s2_age, by = "tagid")

dob_full <- dob_full[-c(19,20)]
colnames(dob_full)[17] <- "W4S1_Age"
colnames(dob_full)[18] <- "W4S2_Age"

write.csv(dob_full, file = "TAG_DOB_SessionDates.csv")


```
