---
title: "Age at Each Wave"
author: "cfm"
date: "`r Sys.Date()`"
output:
	html_document:
		toc: yes
		toc_float:
			collapsed: yes
			smooth_scroll: yes
		number_sections: yes
		theme: superhero
		highlight: default
		fig_width: 7
		fig_height: 6
		fig_caption: yes
		df_print: paged
		code_folding: hide
---

## Setting up markdown {.tabset}

```{r setup, include=FALSE}

knitr::opts_chunk$set(
	echo = TRUE,
	message = TRUE,
	warning = TRUE
)

```
### loading required packages

```{r Load Required Packages, message=FALSE, warning=FALSE, include=FALSE}

# load packages

library(pacman)
pacman::p_load(dplyr, ggplot2, install = TRUE)

```

### setting root path

```{r Setting root path}

## cfm root path

# root_path = "~/Desktop/Repos/tag/"
root_path = "/Volumes/psych-cog/dsnlab/TAG/behavior/Demographics/Age/timeline/"

```
### pulling in data

```{r pulling in csv}

## importing doc pulled from redcap with IDs and all session dates

w1 <- read.csv(paste0(root_path, "w1_dates.csv"),
                     stringsAsFactors = FALSE) %>% 
  select(subject_spit_id, sa_date) %>% 
  mutate(W1_date = sa_date) %>% 
  select(-sa_date)

w2 <- read.csv(paste0(root_path, "w2_dates.csv"),
                     stringsAsFactors = FALSE) %>% 
  select(subject_spit_id, sa_date) %>% 
  mutate(W2_date = sa_date) %>% 
  select(-sa_date)

w3 <- read.csv(paste0(root_path, "w3_dates.csv"),
                     stringsAsFactors = FALSE) %>% 
  select(subject_spit_id, sa_date) %>% 
  mutate(W3_date = sa_date) %>% 
  select(-sa_date)

w4 <- read.csv(paste0(root_path, "w4_dates.csv"),
                     stringsAsFactors = FALSE) %>% 
  select(subject_spit_id, sa_date) %>% 
  mutate(W4_date = sa_date) %>% 
  select(-sa_date)

w5 <- read.csv(paste0(root_path, "w5_dates.csv"),
                     stringsAsFactors = FALSE) %>% 
  select(subject_spit_id, sa_date) %>% 
  mutate(W5_date = sa_date) %>% 
  select(-sa_date)

ace <- read.csv(paste0(root_path, "ace.csv"),
                stringsAsFactors = FALSE)

sos <- read.csv(paste0(root_path, "sos.csv"),
                stringsAsFactors = FALSE)

dob <- read.csv(paste0(root_path, "dob.csv"),
                stringsAsFactors = FALSE) 

```
### loading in age calc function

```{r loading in function (age_calc) to calculate precise age}

age_calc <- function(dob, enddate=Sys.Date(), units='months', precise=TRUE){
  if (!inherits(dob, "Date") | !inherits(enddate, "Date")) {
    stop("Both dob and enddate must be Date class objects")
  }
  if (any(enddate < dob)) {
    stop("End date must be a date after date of birth")
  }
  start <- as.POSIXlt(dob)
  end <- as.POSIXlt(enddate)
  if (precise) {
    start_is_leap <- ifelse(start$year %% 400 == 0, TRUE,
                            ifelse(start$year %% 100 == 0, FALSE,
                                   ifelse(start$year %% 4 == 0, TRUE, FALSE)))
    end_is_leap <- ifelse(end$year %% 400 == 0, TRUE,
                          ifelse(end$year %% 100 == 0, FALSE,
                                 ifelse(end$year %% 4 == 0, TRUE, FALSE)))
  }
  if (units == 'days') {
    result <- difftime(end, start, units = 'days')
  } else if (units == 'months') {
    months <- vapply(mapply(seq, as.POSIXct(start), as.POSIXct(end),
                            by = 'months', SIMPLIFY = FALSE),
                     length, FUN.VALUE = length(start)) - 1
    # length(seq(start, end, by='month')) - 1
    if (precise) {
      month_length_end <- ifelse(end$mon == 1 & end_is_leap, 29,
                                 ifelse(end$mon == 1, 28,
                                        ifelse(end$mon %in% c(3, 5, 8, 10),
                                               30, 31)))
      month_length_prior <- ifelse((end$mon - 1) == 1 & start_is_leap, 29,
                                   ifelse((end$mon - 1) == 1, 28,
                                        ifelse((end$mon - 1) %in% c(3, 5, 8, 10),
                                                 30, 31)))
      month_frac <- ifelse(end$mday > start$mday,
                           (end$mday - start$mday) / month_length_end,
                           ifelse(end$mday < start$mday,
                                  (month_length_prior - start$mday) /
                                    month_length_prior +
                                    end$mday/month_length_end, 0.0))
      result <- months + month_frac
    }else{
      result <- months
    }
  } else if (units == 'years') {
    years <- vapply(mapply(seq, as.POSIXct(start), as.POSIXct(end),
                           by = 'years', SIMPLIFY = FALSE),
                    length, FUN.VALUE = length(start)) - 1
    if (precise) {
      start_length <- ifelse(start_is_leap, 366, 365)
      end_length <- ifelse(end_is_leap, 366, 365)
      start_day <- ifelse(start_is_leap & start$yday >= 60,
                          start$yday - 1,
                          start$yday)
      end_day <- ifelse(end_is_leap & end$yday >= 60,
                        end$yday - 1,
                        end$yday)
      year_frac <- ifelse(start_day < end_day,
                          (end_day - start_day)/end_length,
                          ifelse(start_day > end_day,
                                 (start_length - start_day) / start_length +
                                   end_day / end_length, 0.0))
      result <- years + year_frac
    }else{
      result <- years
    }
  }else{
    stop("Unrecognized units. Please choose years, months, or days.")
  }
  return(result)
}

```
## Cleaning data {.tabset}

```{r Merging and cleaning docs}

## whole doc 

whole <- full_join(w1, full_join(w2,w3, by = "subject_spit_id"), by = "subject_spit_id")
whole <- full_join(whole, full_join(w4, w5, by = "subject_spit_id"), by = "subject_spit_id")

whole <- tidyr::pivot_longer(whole, col = 2:6, names_to = "wave", values_to = "session_date")

#import "overview" document so that we can filter analyses to subjects that were not excluded

overview <- readxl::read_xlsx('/Volumes/psych-cog/dsnlab/TAG/behavior/Overview/Overview_Withdrawn_Completed/TAG_Overview_Doc.xlsx',1) %>% 
  select(TAG_ID, Withdrawn_W1)

overview <- overview[which(overview$Withdrawn_W1 == "0"),]

whole <- whole[which(whole$subject_spit_id %in% overview$TAG_ID),]

## TAG General merge

whole <- full_join(whole, dob, by="subject_spit_id") %>%
   filter(!is.na(session_date),
          !is.na(dob))

## converting to date class

whole$session_date <- as.Date(whole$session_date, format = "%Y-%m-%d")
whole$dob <- as.Date(whole$dob, format = "%Y-%m-%d")
whole <- whole %>% 
  filter(!is.na(session_date))

## calculating age from DOB & session dates

whole$age <- age_calc(whole$dob, enddate = whole$session_date, units = "years", precise = TRUE)

## ACE merge

ace <- ace[-2]

ace <- tidyr::pivot_longer(ace, col = 2:4, values_to = "session_date", names_to = "wave")

ace <- full_join(ace, dob, by="subject_spit_id") %>%
   filter(!is.na(session_date),
          !is.na(dob))

## converting to date class

ace <- ace %>% 
  mutate_all(na_if,"") %>% 
  filter(!is.na(session_date))

ace$session_date <- as.Date(ace$session_date, format = "%Y-%m-%d")
ace$dob <- as.Date(ace$dob, format = "%Y-%m-%d")

## calculating age from DOB & session dates

ace$age <- age_calc(ace$dob, enddate = ace$session_date, units = "years", precise = TRUE)

## SOS 

colnames(sos) <- c("subject_spit_id", "wave", "session_date")

sos <- full_join(sos, dob, by="subject_spit_id") %>%
   filter(!is.na(session_date),
          !is.na(dob))

## converting to date class

sos <- sos %>% 
  mutate_all(na_if,"") %>% 
  filter(!is.na(session_date))

sos$session_date <- as.Date(sos$session_date, format = "%Y-%m-%d")
sos$dob <- as.Date(sos$dob, format = "%Y-%m-%d")

## calculating age from DOB & session dates

sos$age <- age_calc(sos$dob, enddate = sos$session_date, units = "years", precise = TRUE)

##WHOLE DOC 

whole <- full_join(whole, ace)
whole <- full_join(whole, sos)
whole <- whole[-c(4,5)]

## renaming wave labels to be more readable

whole <- whole %>%
  mutate(wave=ifelse(wave=="W1_date", "W1",
                           ifelse(wave=="W2_date","W2",
                                  ifelse(wave=="W3_date","W3",
                                         ifelse(wave=="W4_date", "W4",
                                                ifelse(wave == "W5_date", "W5",
                                                  ifelse(wave=="sos_arm_1","SOS1",
                                                       ifelse(wave=="ace_month1_date","COV1",
                                                              ifelse(wave=="ace_month2_date","COV2",
                                                                     ifelse(wave=="ace_month3_date_3", "COV3",
                              wave)))))))))) %>%
  mutate(wave=as.factor(wave))

## reordering levels

whole$wave <- factor(whole$wave, levels=c("W1", "W2", "SOS1", "W3", "COV1", "W4", "COV2", "COV3", "W5"))


```

```{r actual study design graph w/ shapes !!}

colnames(whole)[1] <- "tagid"
## creating a doc ordering IDs by timepoints, age and ID

study_design <- whole[order(whole$wave, whole$age, whole$tagid),]

## creating levels using ordered doc

whole <- study_design %>%
  mutate(Rank_nr=as.numeric(factor(tagid,levels=unique(tagid))))

## creating visualization

tag_study_design_plot<- ggplot(whole,
                           aes(x=age,
                               y=Rank_nr,
                               group=tagid,
                               col=wave,
                               shape=wave)) +
  geom_point(alpha=1) +
  geom_line(alpha=.4) +
  expand_limits(y=c(0,186))+
  expand_limits(x=c(10,20)) +
  theme(axis.text.y = element_blank()) +
  scale_color_manual(name= "Wave",
                     labels = c("W1", "W2", "SOS1", "W3", "COV1", "COV2", "COV3", "W4", "W5"),
                     values = c("#5445b1", "#749dae", "#f3c483", "#5c1a33", "#cd3341","#FE5D26", "#FFA0AC", "#B4DC7F", "purple"))  +
  scale_shape_manual(name= "Wave",
              labels= c("W1", "W2", "SOS1", "W3", "COV1", "COV2", "COV3", "W4", "W5"),
              values = c(0, 1, 2, 5, 6, 7, 10, 14, 15))+
  ylab("") +
  xlab("Age (years)")+
  scale_y_discrete(breaks=NULL) +
  theme_minimal()

## viewing plot

print(tag_study_design_plot)

## saving png of plot

ggsave(filename=paste0(root_path,"output/tag_study_design_w_shapes.png"),
       plot=tag_study_design_plot, width=6, height=5, units='in', dpi=300)


```

```{r just waves!!}

##creating separate w1-w4 doc

## FOR HONOR THESIS (CFM) - filtering up until 01/13/2020 

whole <- whole %>%
  filter(session_date <= as.Date("0020-01-13"))

wave_1 <- whole[which(whole$wave == "W1"),]
wave_2 <- whole[which(whole$wave == "W2"),]
wave_3 <- whole[which(whole$wave == "W3"),]
#wave_4 <- whole[which(whole$wave == "W4"),]

just_waves <- full_join(wave_1, wave_2)
just_waves <- full_join(just_waves, wave_3)
#just_waves <- full_join(just_waves, wave_4)

## creating a doc ordering IDs by timepoints, age and ID

waves_study_design <- just_waves[order(just_waves$wave, just_waves$age, just_waves$tagid),]

## creating levels using ordered doc

just_waves <- waves_study_design %>%
  mutate(Rank_nr=as.numeric(factor(tagid,levels=unique(tagid))))

## creating visualization

tag_waves_study_design_plot<- ggplot(just_waves,
                           aes(x=age,
                               y=Rank_nr,
                               group=tagid,
                               col=wave,
                               shape=wave)) +
  geom_point(alpha=1) +
  geom_line(alpha=.4) +
  expand_limits(y=c(0,186))+
  theme(axis.text.y = element_blank()) +
  scale_color_manual(name= "Wave",
                     labels = c("W1", "W2", "W3"),
                     values = c("#5445b1", "#5c1a33", "#f3c483"))  +
  scale_shape_manual(name= "Wave",
              labels= c("W1", "W2",  "W3"),
              values = c(0, 1, 2))+
  ylab("") +
  xlab("Age (years)")+
  scale_y_discrete(breaks=NULL) +
  theme_minimal()

## viewing plot

print(tag_waves_study_design_plot)

## saving png of plot

ggsave(filename="tag_wave_precovid_study_design.png",
       plot=tag_waves_study_design_plot, width=5, height=5, units='in', dpi=600, bg = "transparent")



```

```{r just waves 1-3 + sos!!}

##creating separate w1-w3 + sos doc

wave_1 <- whole[which(whole$wave == "W1"),]
wave_2 <- whole[which(whole$wave == "W2"),]
wave_3 <- whole[which(whole$wave == "W3"),]
sos <- whole[which(whole$wave == "SOS1"),]

waves_sos <- full_join(wave_1, wave_2)
waves_sos <- full_join(waves_sos, wave_3)
waves_sos <- full_join(waves_sos, sos)

## creating a doc ordering IDs by timepoints, age and ID

waves_sos_design <- waves_sos[order(waves_sos$wave, waves_sos$age, waves_sos$tagid),]

## creating levels using ordered doc

waves_sos <- waves_sos_design %>%
  mutate(Rank_nr=as.numeric(factor(tagid,levels=unique(tagid))))

## creating visualization

tag_waves_sos_design_plot<- ggplot(waves_sos,
                           aes(x=age,
                               y=Rank_nr,
                               group=tagid,
                               col=wave,
                               shape=wave)) +
  geom_point(alpha=1) +
  geom_line(alpha=.4) +
  theme(axis.text.y = element_blank()) +
  expand_limits(y=c(0,186))+
  scale_color_manual(name= "Wave",
                     labels = c("W1", "W2", "SOS","W3"),
                     values = c("#5445b1", "#749dae", "#ff8c00", "#5c1a33"))  +
  scale_shape_manual(name= "Wave",
              labels= c("W1", "W2", "SOS", "W3"),
              values = c(0, 1, 2, 5))+
  ylab("") +
  xlab("Age (years)")+
  scale_y_discrete(breaks=NULL) +
  theme_minimal()


## viewing plot

print(tag_waves_sos_design_plot)

## saving png of plot

ggsave(filename="tag_waves_sos_design_w_shapes.png",
       plot=tag_waves_sos_design_plot, width=5, height=5, units='in', dpi=600)



```


```{r just ACE}

## sorting IDs by number of timepoints

ace <- whole[which(whole$wave == "COV1" & whole$wave == "COV2" & whole$wave == "COV3"),]

## creating a doc ordering IDs by timepoints, age and ID

study_design_ace <- ace[order(ace$wave, ace$age, ace$tagid),]

## creating levels using ordered doc

ace <- study_design_ace %>%
  mutate(Rank_nr=as.numeric(factor(tagid,levels=unique(tagid))))

## creating visualization

ace_study_design_plot<- ggplot(ace,
                           aes(x=age,
                               y=Rank_nr,
                               group=tagid,
                               col=wave,
                               shape=wave)) +
  geom_point(alpha=1) +
  geom_line(alpha=.4) +
  theme(axis.text.y = element_blank()) +
  scale_color_manual(name= "Wave",
                     labels = c("COV1", "COV2", "COV3"),
                     values = c("#5445b1", "#749dae", "#f3c483"))  +
  scale_shape_manual(name= "Wave",
              labels= c("COV1", "COV2", "COV3"),
              values = c(0, 1, 2))+
  ylab("") +
  xlab("Age (years)")+
  scale_y_discrete(breaks=NULL) +
  theme_minimal()

## viewing plot

print(ace_study_design_plot)

## saving png of plot

ggsave(filename="ace_study_design_w_shapes.png",
       plot=ace_study_design_plot, width=6, height=5, units='in', dpi=300)

```

```{r adding session dates for W4 to TAG_DOB}

dob_full <- read.csv("/Volumes/psych-cog/dsnlab/TAG/behavior/Demographics/Age/TAG_DOB_SessionDates.csv",
                stringsAsFactors = FALSE) %>% 
  select(-W4S1_Date, -W4S1_Age_Months)

w4 <-w4 %>%
  mutate(no_underscores=paste0("TAG",
                               substring(subject_spit_id,first=5,last=length(subject_spit_id))))
 w4 <- w4[c(-1)]
 w4 <- w4[c(2,1)]
 colnames(w4) <- c("tagid", "W4S1_Date")


w5 <- w5 %>%
  mutate(no_underscores=paste0("TAG",
                               substring(subject_spit_id,first=5,last=length(subject_spit_id))))

w5 <- w5[c(-1)]
w5 <- w5[c(2,1)]
colnames(w5) <- c("tagid", "W5S1_Date")

dob_full <- full_join(dob_full, w4, by = "tagid")
dob_full <- full_join(dob_full, w5, by = "tagid")

dob_full  <- dob_full[c(1,2,3,4,5,6,7,8,17,18,9,10,11,12,13,14,15,16)]

 ## converting to date class

dob_full$W4S1_Date <- as.Date(dob_full$W4S1_Date, "%m/%d/%y")
dob_full$W4S2_Date <- as.Date(dob_full$W4S2_Date, "%m/%d/%y")
dob_full$dob <- as.Date(dob_full$dob, "%m/%d/%y")

## calculating age from DOB & session dates

w4s1_age <- dob_full %>%
  filter(!is.na(dob_full$W4S1_Date))

w4s1_age <- w4s1_age %>%
  select(tagid, dob, W4S1_Date)

w4s1_age$W4S1_Age <- age_calc(w4s1_age$dob, enddate = w4s1_age$W4S1_Date, units = "years", precise = TRUE)

w4s2_age <- dob_full %>%
  filter(!is.na(dob_full$W4S2_Date))

w4s2_age <- w4s2_age %>%
  select(tagid, dob, W4S2_Date)

w4s2_age$W4S2_Age <- age_calc(w4s2_age$dob, enddate = w4s2_age$W4S2_Date, units = "years", precise = TRUE)

w4s1_age <- w4s1_age %>%
  select(-dob,-W4S1_Date)

w4s2_age <- w4s2_age %>%
  select(-dob,-W4S2_Date)

dob_full <- full_join(dob_full, w4s1_age, by = "tagid")
dob_full <- full_join(dob_full, w4s2_age, by = "tagid")

dob_full <- dob_full[-c(19,20)]
colnames(dob_full)[17] <- "W4S1_Age"
colnames(dob_full)[18] <- "W4S2_Age"

write.csv(dob_full, file = "TAG_DOB_SessionDates.csv")


```
